name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        pip install gunicorn uvicorn

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 79.174.91.122
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ledovod-ai
          git reset --hard
          git pull origin main --force
          source venv/bin/activate
          pip install -r requirements.txt
          pm2 reload ecosystem.config.js
